xrdfs manage.aglt2.org:1094 query stats a >checkAP_aglt2.log & 
xrdfs dcdoor11.usatlas.bnl.gov:1094 query stats a >checkAP_bnl-atlas.log & 
xrdfs atlas-xrd-eos-n2n.cern.ch:1094 query stats a >checkAP_cern-prod.log & 
xrdfs srm.glite.ecdf.ed.ac.uk:1094 query stats a >checkAP_uki-scotgrid-ecdf.log & 
xrdfs svr018.gla.scotgrid.ac.uk:1094 query stats a >checkAP_uki-scotgrid-glasgow.log & 
xrdfs vobox0004.m45.ihep.su:1094 query stats a >checkAP_ru-protvino-ihep.log & 
xrdfs atlasse.lnf.infn.it:1094 query stats a >checkAP_infn-frascati.log & 
xrdfs t2-dpm-01.na.infn.it:1094 query stats a >checkAP_infn-napoli-atlas.log & 
xrdfs grid-cert-03.roma1.infn.it:1094 query stats a >checkAP_infn-roma1.log & 
xrdfs lcgsexrda.jinr.ru:1094 query stats a >checkAP_jinr-lcg2.log & 
xrdfs xrootd-lrz-lmu.grid.lrz.de:1094 query stats a >checkAP_lrz-lmu.log & 
xrdfs atlas-cm4.bu.edu:1094 query stats a >checkAP_bu_atlas_tier2.log & 
xrdfs tier2-03.ochep.ou.edu:1094 query stats a >checkAP_ou_ochep_swt2.log & 
xrdfs t2se01.physics.ox.ac.uk:1094 query stats a >checkAP_uki-southgrid-ox-hep.log & 
xrdfs golias100.farm.particle.cz:1094 query stats a >checkAP_praguelcg2.log & 
xrdfs xrootd.esc.qmul.ac.uk:1094 query stats a >checkAP_uki-lt2-qmul.log & 
xrdfs gk06.atlas-swt2.org:1094 query stats a >checkAP_swt2_cpb.log & 
xrdfs atl-prod09.slac.stanford.edu:1094 query stats a >checkAP_wt2.log & 
xrdfs up.pleiades.uni-wuppertal.de:1094 query stats a >checkAP_wuppertalprod.log & 
xrdfs fax.mwt2.org:1094 query stats a >checkAP_mwt2.log & 
xrdfs xrootd-mppmu.grid.lrz.de:2094 query stats a >checkAP_mppmu.log & 
xrdfs t2-atlas-xrootd.desy.de query stats a >checkAP_desy-hh.log & 
xrdfs hepgrid11.ph.liv.ac.uk query stats a >checkAP_uki-northgrid-liv-hep.log & 
xrdfs fal-pygrid-30.lancs.ac.uk:1094 query stats a >checkAP_uki-northgrid-lancs-hep.log & 
xrdfs serv02.hep.phy.cam.ac.uk query stats a >checkAP_uki-southgrid-cam-hep.log & 
xrdfs bohr3226.tier2.hep.manchester.ac.uk:1094 query stats a >checkAP_uki-northgrid-man-hep.log & 
xrdfs grid05.lal.in2p3.fr:1094 query stats a >checkAP_grif-lal.log & 
xrdfs lapp-se01.in2p3.fr:11000 query stats a >checkAP_in2p3-lapp.log & 
xrdfs lpnse1.in2p3.fr:1094 query stats a >checkAP_grif-lpnhe.log & 
xrdfs node12.datagrid.cea.fr:1094 query stats a >checkAP_grif-irfu.log & 
xrdfs marsedpm.in2p3.fr:1094 query stats a >checkAP_in2p3-cppm.log & 
xrdfs f01-140-115-e.gridka.de:1094 query stats a >checkAP_fzk-lcg2.log & 
xrdfs lcg-xrd.ifh.de:1094 query stats a >checkAP_desy-zn.log & 
xrdfs sedoor1.bfg.uni-freiburg.de query stats a >checkAP_uni-freiburg.log & 
xrdfs atlas-xrd.gridpp.rl.ac.uk:1094 query stats a >checkAP_ral-lcg2.log & 
xrdfs se-xrootd.goegrid.gwdg.de:1094 query stats a >checkAP_goegrid.log & 
xrdfs f-dpm000.grid.sinica.edu.tw:11000 query stats a >checkAP_taiwan-lcg2.log & 
xrdfs xrootd-atlas.cr.cnaf.infn.it:1094 query stats a >checkAP_infn-t1.log & 
xrdfs lpsc-se-dpm-server.in2p3.fr:11000 query stats a >checkAP_in2p3-lpsc.log & 
xrdfs se.reef.man.poznan.pl:1094 query stats a >checkAP_psnc.log & 
xrdfs dpm.cyf-kr.edu.pl:1094 query stats a >checkAP_cyfronet-lcg2.log & 
xrdfs lcgse0.shef.ac.uk:1094 query stats a >checkAP_uki-northgrid-shef-hep.log & 
xrdfs se2.ppgrid1.rhul.ac.uk:1094 query stats a >checkAP_uki-lt2-rhul.log & 
xrdfs grid05.unige.ch:1094 query stats a >checkAP_unige-dpnc.log & 
xrdfs gridftp-a1-1.mi.infn.it:1094/ query stats a >checkAP_infn-milano-atlasc.log & 
xrdfs atlas-xrd-ru.cern.ch:1094 query stats a >checkAP_XROOTD-atlas-xrd-ru.log & 
xrdfs atlas-xrd-eu.cern.ch:1094 query stats a >checkAP_XROOTD_atlas-xrd-eu.log & 
xrdfs glrd.usatlas.org:1094 query stats a >checkAP_XROOTD_glrd.log & 
xrdfs atlas-xrd-uk.cern.ch:1094 query stats a >checkAP_XROOTD-atlas-xrd-uk.log & 
xrdfs atlas-xrd-de.cern.ch:1094 query stats a >checkAP_XROOTD-atlas-xrd-de.log & 
xrdfs atlas-xrd-it.cern.ch:1094 query stats a >checkAP_XROOTD-atlas-xrd-it.log & 
xrdfs xrd-central.usatlasfacility.org:1094 query stats a >checkAP_XROOTD-xrd-central.log & 
xrdfs atlas-xrd-fr.cern.ch:1094 query stats a >checkAP_XROOTD-atlas-xrd-fr.log & 
xrdfs atlas-xrd-asia.grid.sinica.edu.tw query stats a >checkAP_XROOTD-atlas-xrd-asia-tw.log & 
