./createTestFiles.sh uki-southgrid-ox-hep	
./createTestFiles.sh uki-northgrid-lancs-hep	
./createTestFiles.sh uki-northgrid-man-hep	
./createTestFiles.sh ifae				  
./createTestFiles.sh cyfronet-lcg2		  
./createTestFiles.sh in2p3-cppm			  
./createTestFiles.sh mwt2				  
./createTestFiles.sh ru-protvino-ihep	  
./createTestFiles.sh in2p3-lpsc			  
./createTestFiles.sh uki-northgrid-shef-hep
./createTestFiles.sh infn-napoli-atlas	  
./createTestFiles.sh praguelcg2			  
./createTestFiles.sh grif-lal			  
./createTestFiles.sh desy-hh				  
./createTestFiles.sh swt2_cpb			  
./createTestFiles.sh uki-southgrid-cam-hep 
./createTestFiles.sh in2p3-lapp			  
./createTestFiles.sh bu_atlas_tier2		  
./createTestFiles.sh fzk-lcg2			  
./createTestFiles.sh infn-t1				  
./createTestFiles.sh wt2					
./createTestFiles.sh infn-roma1			  
./createTestFiles.sh goegrid				  
./createTestFiles.sh uni-freiburg		  
./createTestFiles.sh grif-lpnhe			  
./createTestFiles.sh ou_ochep_swt2		  
./createTestFiles.sh bnl-atlas			  
./createTestFiles.sh grif-irfu			  
./createTestFiles.sh uki-lt2-qmul		  
./createTestFiles.sh uki-scotgrid-glasgow  
./createTestFiles.sh taiwan-lcg2			  
./createTestFiles.sh lrz-lmu				  
./createTestFiles.sh aglt2				  
./createTestFiles.sh desy-zn				  
./createTestFiles.sh infn-frascati		  
./createTestFiles.sh psnc				  
./createTestFiles.sh ral-lcg2			  
./createTestFiles.sh mppmu				  
./createTestFiles.sh jinr-lcg2			  
./createTestFiles.sh wuppertalprod		  
./createTestFiles.sh uki-northgrid-liv-hep 
./createTestFiles.sh uki-scotgrid-ecdf	  
./createTestFiles.sh pic					
./createTestFiles.sh cern-prod
